from snakemake.utils import min_version
from snakemake.logging import logger
import subprocess
import sys
import os
from propinquity import (gen_config_content,
                         gen_otc_config_content,
                         validate_config,
                         write_if_needed,
                         )
import json
from peyutil import write_as_json

min_version("5.31.1")

CFG = validate_config(config, logger)
content = json.dumps(config, sort_keys=True, indent=2) + '\n'
write_if_needed(content=content, fp="config.json", CFG=CFG)

workdir: CFG.out_dir
configfile: "config.json"

module common:
    snakefile: "rules/common.smk"
    config: config

module s00_tool_config:
    snakefile: "rules/s00_tool_config.smk"
    config: config

module s01_snapshot:
    snakefile: "rules/s01_snapshot.smk"
    config: config

module s02_clean_ott:
    snakefile: "rules/s02_clean_ott.smk"
    config: config

module s03_clean_phylo:
    snakefile: "rules/s03_clean_phylo.smk"
    config: config

module s04_modify_taxonomy:
    snakefile: "rules/s04_modify_taxonomy.smk"
    config: config

module s05_exemplify:
    snakefile: "rules/s05_exemplify.smk"
    config: config

module s06_subproblems:
    snakefile: "rules/s06_subproblems.smk"
    config: config

module s07_subproblems_deg_dist:
    snakefile: "rules/s07_subproblems_deg_dist.smk"
    config: config

module s08_graft:
    snakefile: "rules/s08_graft.smk"
    config: config

module s09_unprune_taxa:
    snakefile: "rules/s09_unprune_taxa.smk"
    config: config

module s10_finish:
    snakefile: "rules/s10_finish.smk"
    config: config

# use rule * from common as common_*
use rule * from s00_tool_config as tool_conf_*
use rule * from s01_snapshot as snap_*
use rule * from s02_clean_ott as clean_ott_*
use rule * from s03_clean_phylo as clean_phylo_*
use rule * from s04_modify_taxonomy as modify_taxonomy_*
use rule * from s05_exemplify as exemplify_*
use rule * from s06_subproblems as subproblems_*
use rule * from s07_subproblems_deg_dist exclude common_* as subproblems_deg_dist_*
use rule * from s08_graft exclude common_* as graft_*
use rule * from s09_unprune_taxa as unprune_taxa_*
use rule * from s10_finish as finish_*

ruleorder: subproblems_common_decompose > graft_common_decompose > subproblems_deg_dist_common_decompose
ruleorder: subproblems_common_cleancontest > graft_common_cleancontest > subproblems_deg_dist_common_cleancontest
ruleorder: subproblems_common_solved_ids > graft_common_solved_ids > subproblems_deg_dist_common_solved_ids
ruleorder: subproblems_common_rev_solved_ids > graft_common_rev_solved_ids > subproblems_deg_dist_common_rev_solved_ids
ruleorder: subproblems_common_reverse_subproblems_flag > graft_common_reverse_subproblems_flag > subproblems_deg_dist_common_reverse_subproblems_flag
ruleorder: subproblems_common_reverse_subproblems > graft_common_reverse_subproblems > subproblems_deg_dist_common_reverse_subproblems



rule all:
    input: "config", 
           "otc-config",
           "checksum_for_run.md5",
           "cleaned_ott/cleaned_not_updated_ott.tre",
           "exemplified_phylo/args.txt",
           "cleaned_phylo/phylo_inputs_cleaned.txt",
           "bumped_ott/cleaned_ott.tre",
           "exemplified_phylo/incertae_sedis.txt",
           "subproblems/raw_contesting_trees.json",
           "subproblems/contesting_trees.json",
           "subproblems/.all_deg_dist_calculated.txt",
           "subproblem_solutions/subproblems-scaffold.tre",
           "subproblem_solutions/subproblems-scaffold-only.tre",
           "subproblem_solutions/solution-ids.txt",
           "reversed_subproblem_solutions/solution-ids.txt",
           "subproblem_solutions/solution-degree-distributions.txt",
           "reversed_subproblem_solutions/solution-degree-distributions.txt",
           "subproblems/.all_deg_dist_calculated.txt",
           "grafted_solution/grafted_solution_ottnames.tre",
           "labelled_supertree/labelled_supertree.tre",
           "labelled_supertree/labelled_supertree_out_degree_distribution.txt",
           "labelled_supertree/labelled_supertree_ottnames.tre",
           "labelled_supertree/labelled_supertree_simplified_ottnames.tre",
           "labelled_supertree/labelled_supertree_ottnames_without_monotypic.tre",
           "labelled_supertree/labelled_supertree_simplified_ottnames_without_monotypic.tre",
           "exemplified_phylo/pruned_taxonomy_degree_distribution.txt",
           "annotated_supertree/annotations.json",
           "index.html",
           "subproblems/subproblem_size_summary_table.tsv",

rule presolve:
    input: "config", \
           "otc-config", \
           "checksum_for_run.md5",
           "cleaned_ott/cleaned_not_updated_ott.tre",
           "exemplified_phylo/args.txt",
           "cleaned_phylo/phylo_inputs_cleaned.txt",
           "bumped_ott/cleaned_ott.tre",
           "exemplified_phylo/incertae_sedis.txt",
           "subproblems/raw_contesting_trees.json",
           "subproblems/contesting_trees.json",
           "subproblems/.all_deg_dist_calculated.txt"

rule solve:
    input: "subproblem_solutions/solution-ids.txt",
           "reversed_subproblem_solutions/solution-ids.txt",

rule calcdd:
    input: "subproblem_solutions/solution-degree-distributions.txt", \
           "reversed_subproblem_solutions/solution-degree-distributions.txt", \
           

rule postsolve:
    input: "grafted_solution/grafted_solution_ottnames.tre",
           "labelled_supertree/labelled_supertree.tre",
           "labelled_supertree/labelled_supertree_out_degree_distribution.txt",
           "labelled_supertree/labelled_supertree_ottnames.tre",
           "labelled_supertree/labelled_supertree_simplified_ottnames.tre",
           "labelled_supertree/labelled_supertree_ottnames_without_monotypic.tre",
           "labelled_supertree/labelled_supertree_simplified_ottnames_without_monotypic.tre",
           "exemplified_phylo/pruned_taxonomy_degree_distribution.txt",
           "annotated_supertree/annotations.json",
           "index.html",
           "subproblems/subproblem_size_summary_table.tsv"

rule prechecksum_inputs:
    input: "config", 
           "otc-config",
           "phylo_snapshot/ps_shard_shas.txt",
           "phylo_snapshot/collections_shard_shas.txt",

rule checksum_inputs:
    input: "config", 
           "otc-config",
           "phylo_snapshot/ps_shard_shas.txt",
           "phylo_snapshot/collections_shard_shas.txt",
           "checksum_for_run.md5",

