#!/usr/bin/Rscript

## Read arguments
args = commandArgs(trailingOnly=T)

## Default setting when no arguments passed
if(length(args) < 1) {
  args <- c("--help")
}
 
## Parse arguments (we expect the form --arg=value)
parseArgs <- function(x) strsplit(sub("^--", "", x), "=")
argsDF <- as.data.frame(do.call("rbind", parseArgs(args)))
argsL <- as.list(as.character(argsDF$V2))
#print("argsL")
#print(argsL)
#print("argsDF$V1")
#print(argsDF$V1)
#print("argsDF$V2")
#print(argsDF$V2)
names(argsL) <- argsDF$V1

## Error conditions
error = FALSE
error = error || !("input" %in% names(argsL))

## Help section
if(("--help" %in% args) || error) {
  cat("The R Script
 
      Input arguments:
      --input=filename         - a newick input file

      Output arguments
      --output=filename        - a PDF output file
      --width=someValue        - width in inches
      --height=someValue       - height in inches
      --format=PDF             - SVG or PDF

      Plotting arguments:
      --type=someValue         - numeric, blah blah
      --edge.width=someValue   - character, blah blah
      --show.node.label=BOOL   - boolean, show internal node labels

      Other arguments:
      --help                   - print this text
 
      Example:
      ./drawtree --input=<newick> --type=cladogram\n\n")
 
  q(save="no")
}


require(ape)
require(phytools)
input = argsL$input
#tree = read.tree(input)
tree = read.newick(input)
plotArgs = list(tree,no.margin=TRUE)

## Set output file if not given
if (!("format" %in% names(argsL)))
    argsL$format = "PDF"

format = tolower(argsL$format)
    
if (!("output" %in% names(argsL)))
   argsL$output = paste0(basename(argsL$input), "." , format)

if ("type" %in% names(argsL))
    plotArgs$type = argsL$type

if ("edge.width" %in% names(argsL))
    plotArgs$edge.width = argsL$edge.width

if ("show.node.label" %in% names(argsL))
    plotArgs$show.node.label = as.logical(argsL$show.node.label)

w = 0.20*max(node.depth(tree)) +2
h = length(tree$tip.label)*0.35
if ("width" %in% names(argsL))
    w = as.numeric(argsL$width)
if ("height" %in% names(argsL))
    h = as.numeric(argsL$height)

print(argsL)
print(plotArgs)

output = argsL$output

#par(oma=c(0,0,0,0))
#par(mar=c(0,0,0,0))
if (format == "pdf") {
    pdf(output,width=w,height=h)
} else if (format == "svg") {
    svg(output,width=w,height=h)
} else {
    stop("Don't recognize format")
}

do.call(plotTree,plotArgs) #plot(tree,type="cladogram",edge.width=argsL$edge.width)

